---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.${NAME} = "${NAME}"
loadClass(_cn.${NAME})

--- Imports ---

---@class ${NAME} : Annotation
local ${NAME} = extends(_cn.${NAME}, _cn.Annotation);

--- Attributs ---


--- Methods ---

function ${NAME}.new(tableRef,attr,params)
---@type ${NAME}
local self = initMetatable(${NAME});
self.innerTable = tableRef;
self.innerAttr = attr;
self.params = params;
return self;
end

function ${NAME}:onValueChange(object,attr,value)
error("Not implemented method")
end

_a.${NAME} = annotation(_cn.${NAME}, ${NAME})
_c.${NAME} = ${NAME}
classloaded(_cn.${NAME})