---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 20/12/2023 15:18
---
-----@type StringUtils
--local StringUtils = import("StringUtils")
--
-----@type Instance
--local Instance = import("Instance")
--
--local newInstance = Instance.new();
--newInstance.test = "Hello World";
--
--print(StringUtils:toString())
--
--print("===>", StringUtils:split("Hello World", " "));

---@type PlayerModule
local PlayerModule = import("PlayerModule")

local p = PlayerModule.new();
p.name = "Hello World";

print("p1",p.name);

local p2 = PlayerModule.new();
p2.name = nil;


-----@type Instance
--local Instance = import("Instance")
--
--local i = Instance.new();
--i.test = "Hello World";
--print("TESTTTT");