---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 26/12/2023 10:41

local love = require("love")
local atsCore = require("ats/ats-core")
local interface = require("ats/interface")

require "love.filesystem"

function requireDirectory( dir )
    dir = dir or ""
    local entities = love.filesystem.getDirectoryItems(dir)

    for k, ents in ipairs(entities) do

        local info = love.filesystem.getInfo(dir .. "/" .. ents)

        if info.type == "file" then
            Ats.thread(function()
                print(dir .. "/" .. ents)
                local fichier = love.filesystem.newFile(dir .. "/" .. ents)
                local contenu
                if fichier:open('r') then
                    contenu = fichier:read()
                    fichier:close()
                else
                    contenu = "Impossible de lire le fichier."
                end
                load(contenu)()
            end)
        else
            requireDirectory(dir .. "/" .. ents)
        end
    end
end

function drawRotatedRectangle(mode, x, y, width, height, angle)
    -- We cannot rotate the rectangle directly, but we
    -- can move and rotate the coordinate system.
    love.graphics.push()
    love.graphics.translate(x, y)
    love.graphics.rotate(angle)
    love.graphics.rectangle(mode, 0, 0, width, height) -- origin in the top left corner
    --	love.graphics.rectangle(mode, -width/2, -height/2, width, height) -- origin in the middle
    love.graphics.pop()
end

local angle = 0
local keyToListen = "space"
local mouseButtonToListen = 1
function love.update(dt)
    angle = angle + dt * 1 -- Rotate at one radian per second.
    if love.keyboard.isDown(keyToListen) then
        print("space pressed")
    end
    if love.mouse.isDown(mouseButtonToListen) then
        print("mouse button pressed")
    end
end

function drawImage(image)
    love.graphics.draw(image, 0, 0)
end

local spritesheet = nil
local sprite1 = nil
local sprite2 = nil

function love.draw()
    --drawRotatedRectangle("fill", 150,150, 100,60, angle)

    love.graphics.setColor(1,1,1,1)
    love.graphics.rectangle("fill", 0,0, 100, 100)
    ---love.graphics.draw(spritesheet, sprite1, x1, y1, rotation1, scaleX1, scaleY1)
    love.graphics.draw(spritesheet, sprite1, 0,0)

end



function love.load()

    Ats.thread(function()
        requireDirectory("ats/core")
        requireDirectory("ats/shared/classes")
    end)

    Ats.thread(function()
        local fichier = love.filesystem.newFile("test.lua")
        local contenu
        if fichier:open('r') then
            contenu = fichier:read()  -- Lire tout le contenu du fichier
            fichier:close()           -- Toujours fermer le fichier après utilisation
        else
            contenu = "Impossible de lire le fichier."
        end
    end)

    Ats.coroutineManager:run()

    spritesheet = love.graphics.newImage("assets/image/isometric-sandbox-sheet.png")
    sprite1 = love.graphics.newQuad(0, 0, 32, 32, spritesheet:getDimensions())
    sprite2 = love.graphics.newQuad(32, 0, 32, 32, spritesheet:getDimensions())
end

