---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:07
---

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:00
---

_cn.Event = "Event"
loadClass(_cn.Event)

---@type Signal
local Signal = import("Signal");

---@class Event : Instance
---@field name string
---@field onEvent Signal
local Event = extends("Event","Instance");

Event.name = ""
Event.onEvent = ""

function Event.new(name)

	local self = metatable({},{__index = Event});
	self.name = name;
	self.onEvent = Signal.new();
	--- FIVEM LINK CODE
	self.event = AddEventHandler(name, function(...)
		self.onEvent:fire(...);
	end);

	return self;
end

function Event:fire(...)
	--- FIVEM LINK CODE
	TriggerEvent(self.name, ...);
end

function Event:Destroy()
	--- FIVEM LINK CODE
	RemoveEventHandler(self.event);
end

_c.Event = Event
classloaded(_cn.Event)
