---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:05
---

---@class PlayerModule : Module
local PlayerModule = extends("PlayerModule", "Module");

_a.NotEmptyAnnotation(PlayerModule,"name")

function PlayerModule.new()
	---@type PlayerModule
	local self = initMetatable(PlayerModule);

	self.name = "PlayerModule";

	return self;
end

_a.Permission(PlayerModule,"restricted",{ role = "admin"})
function PlayerModule:restricted()
	return true;
end