---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 23/12/2023 13:24
---

Project = {
    plateform = "Fivem",
    game = "gta5",
    environment = "dev",
    version = "0.0.1",
    author = "Absolute",
    name = "AbsoluteTS",
    isDebug = true,
    isDev = function()
        return Project.environment == "dev"
    end,
    paths = {

    },
    defaultPed = "a_m_y_skater_01",
    timeScale = 1.0, -- for seconds => 1000 for ms
}