---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.NotEmptyAnnotation = "NotEmptyAnnotation"
loadClass(_cn.NotEmptyAnnotation)

---@class NotEmptyAnnotation : Annotation
local NotEmptyAnnotation = extends("NotEmptyAnnotation", "Annotation");

function NotEmptyAnnotation.new(tableRef,attr,params)
	---@type NotEmptyAnnotation
	local self = setmetatable({}, { __index = NotEmptyAnnotation });
	self.innerTable = tableRef;
	self.innerAttr = attr;
	self.params = params;
	return self;
end

---@param value string
---@return boolean
function NotEmptyAnnotation:onValueChange(object,attr,value)
	if (value == nil or value == "") then
		error("Value cannot be nil")
	end
	print("Value changed to: " .. value);
end

_a.NotEmptyAnnotation = annotation(_cn.NotEmptyAnnotation, NotEmptyAnnotation)
_c.NotEmptyAnnotation = NotEmptyAnnotation
classloaded(_cn.NotEmptyAnnotation)