---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.Regex = "Regex"
loadClass(_cn.Regex)

--- Imports ---

---@class Regex : Annotation
---@field params {regex:string}
local Regex = extends(_cn.Regex, _cn.Annotation);

--- Attributs ---

--- Methods ---

function Regex.new(tableRef, attr, params)
    ---@type Regex
    local self = initMetatable(Regex);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;
    return self;
end

function Regex:onValueChange(object, attr, value)
    if type(value) ~= "string" then
        error("Value must be a string")
    end

    if (not string.match(value, self.params.regex)) then
        error("Value must match regex: " .. self.params.regex)
    end
end

_a.Regex = annotation(_cn.Regex, Regex)
_c.Regex = Regex
classloaded(_cn.Regex)