---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

loadClass("Test")

---@type TestBench
local TestBench = import("TestBench");

---@class Test : Annotation
local Test = extends("Test", "Annotation");

--- Attributs ---


--- Methods ---

function Test.new(tableRef, attr, params)
    ---@type Test
    local self = initMetatable(Test);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;

    Interface.thread(function()
        ---@type TestBench
        local TestBench = getSingleton(TestBench)
        TestBench.nbTest = TestBench.nbTest + 1;
        singleton(tableRef.__class__)
        local instance = getSingleton(tableRef)
        instance.testBench = TestBench;
        instance:test();
    end)

    return self;
end

function Test:onValueChange(object, attr, value)
    error("Not implemented method")
end

_a.Test = annotation("Test", Test)
_c.Test = Test
_cn.Test = "Test"
classloaded("Test")