---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.Permission = "Permission"
loadClass(_cn.Permission)

---@class Permission : Annotation
local Permission = extends("Permission", "Annotation");

--- Attributs ---


--- Methods ---

function Permission.new(tableRef, attr, params)
    ---@type Permission
    local self = initMetatable(Permission);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;



    return self;
end

function Permission:onValueChange(object, attr, value)

end

function Permission:onInstantiate(object, attr, value)
    local defaultFct = object[attr];
    object[attr] = function(...)
        print("Permission check")
        defaultFct(...)
    end
end

_a.Permission = annotation(_cn.Permission, Permission)
_c.Permission = Permission
classloaded(_cn.Permission)