---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jokir.
--- DateTime: 23/12/2023 14:49
---

Enum.Scope = {
    SINGLETON = "SINGLETON",
    PROTOTYPE = "PROTOTYPE",
    REQUEST = "REQUEST",
    SESSION = "SESSION",
    VIEW = "VIEW"
}