---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.MaxLength = "MaxLength"
loadClass(_cn.MaxLength)

--- Imports ---

---@class MaxLength : Annotation
---@field params {length:number}
local MaxLength = extends("MaxLength", "Annotation");

--- Attributs ---


--- Methods ---

function MaxLength.new(tableRef, attr, params)
    ---@type MaxLength
    local self = initMetatable(MaxLength);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;
    return self;
end

function MaxLength:onValueChange(object, attr, value)
    if type(value) ~= "string" then
        error("Value must be a string")
    end
    if (#value > self.params.length) then
        error("Value cannot be nil")
    end
end

_a.MaxLength = annotation(_cn.MaxLength, MaxLength)
_c.MaxLength = MaxLength
classloaded(_cn.MaxLength)