---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.NumberInterval = "NumberInterval"
loadClass(_cn.NumberInterval)

--- Imports ---

---@class NumberInterval : Annotation
---@field params {min:number,max:number}
local NumberInterval = extends("NumberInterval", "Annotation");

--- Attributs ---


--- Methods ---

function NumberInterval.new(tableRef, attr, params)
    ---@type NumberInterval
    local self = initMetatable(NumberInterval);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;
    return self;
end

function NumberInterval:onValueChange(object, attr, value)
    if type(value) ~= "number" then
        error("Value must be a number")
    end

    if (value < self.params.min) then
        error("Value must be greater than " .. self.params.min)
    end

    if (value > self.params.max) then
        error("Value must be less than " .. self.params.max)
    end
end

_a.NumberInterval = annotation(_cn.NumberInterval, NumberInterval)
_c.NumberInterval = NumberInterval
classloaded(_cn.NumberInterval)