---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 00:28
---

---@type Signal
local Signal = import("Signal");

---@class Instance : BaseObject
---@field className string
---@field parent Instance
---@field children table<number, Instance>
---@field properties table<string, Instance>
---@field events table<string, Instance>
---@field connections table<string, Connection>
---@field changed Signal
local Instance = class("Instance");

function Instance.new(className, parent)
	local signal = Signal.new();
	local analyzeStack =function(table, key, value)
		if value ~= "function" then
			signal:fire(key, value)
		end
	end;
	local self = initMetatable(Instance,function(table, key, value)
		if value ~= "function" then
			signal:fire(key, value)
		end
	end);
	self.className = className;
	self.parent = parent;
	self.children = {};
	self.changed = signal
	return self;
end

function Instance:Destroy()
	for _, child in pairs(self.children) do
		child:Destroy();
	end
	for _, connection in pairs(self.connections) do
		connection:Disconnect();
	end
	self.children = {};
	self.parent = nil;
end