---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.StringUtils = "StringUtils";
loadClass(_cn.StringUtils)
---@class StringUtils : BaseObject
local StringUtils = class("StringUtils");

function StringUtils.new()
	local self = setmetatable({}, { __index = StringUtils });
	return self;
end

function StringUtils:split(str, sep)
	local result = {};
	local regex = ("([^%s]+)"):format(sep);
	for each in str:gmatch(regex) do
		table.insert(result, each);
	end
	return result;
end

function StringUtils:startsWith(str, start)
	return str:sub(1, #start) == start;
end

function StringUtils:endsWith(str, ending)
	return ending == "" or str:sub(-#ending) == ending;
end

function StringUtils:contains(str, contains)
	return str:find(contains) ~= nil;
end

_c.StringUtils = StringUtils;
classloaded(_cn.StringUtils)
singleton(_cn.StringUtils);

