---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:21
---

_cn.Annotation = "Annotation"
loadClass(_cn.Annotation)
---@class Annotation : BaseObject
local Annotation = class(_cn.Annotation);

function Annotation.new(tableRef,attr,params)
	---@type Annotation
	local self = setmetatable({}, { __index = Annotation });
	self.innerTable = tableRef;
	self.innerAttr = attr;
	self.params = params;

	return self;
end

function Annotation:setInnerTable(innerTable)
	self.innerTable = innerTable;
end

function Annotation:setInnerAttr(innerAttr)
	self.innerAttr = innerAttr;
end

function Annotation:onValueChange(object,attr)
	error("Not implemented")
end

function Annotation:onInstantiate(object,attr)

end

_c.Annotation = Annotation
classloaded("Annotation")