---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:00
---

_cn.RemoteEvent = "RemoteEvent"
loadClass(_cn.RemoteEvent)

---@type Signal
local Signal = import("Signal");

---@class RemoteEvent : Instance
local RemoteEvent = extends("RemoteEvent","Instance");

function RemoteEvent.new(name)
	local self = initMetatable(RemoteEvent);
	self.name = name;
	self.onClient = Signal.new();
	self.onServer = Signal.new()
	--- FIVEM LINK CODE
	self.netEvent = RegisterNetEvent(name, function(...)
		if IsDuplicityVersion() then
			self.onServer:fire(...);
		else
			self.onClient:fire(...);
		end
	end);

	return self;
end

function RemoteEvent:fireClient(playerId, ...)
	--- FIVEM LINK CODE
	TriggerClientEvent(self.name, playerId, ...);
end

function RemoteEvent:fireAllClients(...)
	--- FIVEM LINK CODE
	TriggerClientEvent(self.name, -1, ...);
end

function RemoteEvent:fireServer(...)
	--- FIVEM LINK CODE
	TriggerServerEvent(self.name, ...);
end

function RemoteEvent:Destroy()
	--- FIVEM LINK CODE
	RemoveEventHandler(self.netEvent);
end

_c.RemoteEvent = RemoteEvent
classloaded(_cn.RemoteEvent)