---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 11:24
---

_cn.ApplicationScope = "ApplicationScope"
loadClass(_cn.ApplicationScope)

---@type DependencyInjection
local DependencyInjection = import("DependencyInjection");

---@class ApplicationScope : Annotation
local ApplicationScope = extends("ApplicationScope", "Annotation");

function ApplicationScope.new(tableRef, attr, params)
    ---@type ApplicationScope
    local self = initMetatable(ApplicationScope);
    self.innerTable = tableRef;
    self.innerAttr = attr;
    self.params = params;
    Interface.thread(function()
        local DependencyInjection = getSingleton(DependencyInjection);
        DependencyInjection:registerInjectableCandidat(tableRef.__class__, Enum.Scope.SINGLETON)
        singleton(tableRef.__class__)
    end)
    return self;
end

function ApplicationScope:onValueChange(object, attr, value)
    error("Not implemented method")
end

_a.ApplicationScope = annotation(_cn.ApplicationScope, ApplicationScope)
_c.ApplicationScope = ApplicationScope
classloaded(_cn.ApplicationScope)