---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 21/12/2023 01:18
---

_cn.Dev = "Dev";
loadClass(_cn.Dev)
---@class Dev : BaseObject
local Dev = class("Dev");

function Dev.new()
	local self = setmetatable({}, { __index = Dev });

	RegisterCommand("dCoords", function()
		local coords = GetEntityCoords(PlayerPedId());
		print(coords.x..", "..coords.y..", "..coords.z);
	end, false);

	return self;
end

_c.Dev = Dev;
classloaded(_cn.Dev)
singleton(_cn.Dev);